CREATE TABLE [dbo].[Invoice]
(
	[InvoiceId]                 NVARCHAR(14)    PRIMARY KEY NOT NULL,
	[InvoicedDate]              DATETIME2(7)    ,
	[DueDate]					DATETIME2(7)    ,
	[InvoiceRef]                NVARCHAR(14)	,
	[IsPaid]					BIT				,
	[InternalCompanyId]         NVARCHAR(14)    ,
	[NoteToRecipient]	        NVARCHAR(14)    ,
	[TermsAndConditions]        NVARCHAR(14)    ,
	[TaxId]						NVARCHAR(14)    ,
	[ItemsValue]			    MONEY			,
	[Delivery]				    MONEY			,
	[Discount]				    MONEY			,
	[SubTotal]				    MONEY			,
	[TaxAmount]					MONEY			,
	[GrandTotal]			    MONEY			,
	[CreatedAt]                 DATETIME2(7)    NOT NULL,
	[ModifiedDate]              DATETIME2(7)    NOT NULL,
)
