CREATE TABLE [dbo].[CustomerInvoice] (
    [CustomerInvoiceId]  NVARCHAR (450)  NOT NULL,
    [HasChild]           NVARCHAR (MAX)  NULL DEFAULT NULL,
    [CreatedAt]          DATETIME2 (7)   NOT NULL,
    [CustomerId]         NVARCHAR (450)  NOT NULL,
    [Discount]           MONEY NOT NULL,
    [DueDate]            DATETIME2 (7)   NOT NULL,
    [GrandTotal]         MONEY NOT NULL,
    [InvoiceDate]        DATETIME2 (7)   NOT NULL,
    [InvoiceNumber]      NVARCHAR (MAX)  NOT NULL,
    [InvoiceReference]   NVARCHAR (MAX)  NULL DEFAULT NULL,
    [IsPaid]             BIT             NOT NULL,
    [BaseCompanyId]      NVARCHAR (450)  NOT NULL,
    [NoteToRecipient]    NVARCHAR (MAX)  NULL DEFAULT NULL,
    [Delivery]           MONEY NOT NULL,
    [SubTotal]           MONEY NOT NULL,
    [TaxAmount]          MONEY NOT NULL,
    [TermsAndConditions] NVARCHAR (MAX)  NULL DEFAULT NULL,
    CONSTRAINT [PK_CustomerInvoice] PRIMARY KEY CLUSTERED ([CustomerInvoiceId] ASC),
    CONSTRAINT [FK_CustomerInvoice_Customer_CustomerId] FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[Customer] ([CustomerId]),
    CONSTRAINT [FK_CustomerInvoice_BaseCompany_BaseCompanyId] FOREIGN KEY ([BaseCompanyId]) REFERENCES [dbo].[BaseCompany] ([BaseCompanyId])
);
