CREATE TABLE [dbo].[VendorInvoice] (
    [VendorInvoiceId]       NVARCHAR (450)  NOT NULL,
    [HasChild]              NVARCHAR (MAX)  NULL DEFAULT NULL,
    [CreatedAt]             DATETIME2 (7)   NOT NULL,
    [Discount]              MONEY NOT NULL,
    [DueDate]               DATETIME2 (7)   NOT NULL,
    [GrandTotal]            MONEY NOT NULL,
    [InvoiceDate]           DATETIME2 (7)   NOT NULL,
    [InvoiceNumber]         NVARCHAR (MAX)  NOT NULL,
    [InvoiceReference]      NVARCHAR (MAX)  NULL DEFAULT NULL,
    [IsPaid]                BIT             NOT NULL,
    [BaseCompanyId]         NVARCHAR (450)  NOT NULL,
    [Note]                  NVARCHAR (MAX)  NULL DEFAULT NULL,
    [OriginalInvoiceNumber] NVARCHAR (MAX)  NOT NULL,
    [Delivery]              MONEY NOT NULL,
    [SubTotal]              MONEY NOT NULL,
    [TaxAmount]             MONEY NOT NULL,
    [TermsAndConditions]    NVARCHAR (MAX)  NULL DEFAULT NULL,
    [VendorId]              NVARCHAR (450)  NOT NULL,
    CONSTRAINT [PK_VendorInvoice] PRIMARY KEY CLUSTERED ([VendorInvoiceId] ASC),
    CONSTRAINT [FK_VendorInvoice_MyCompany_BaseCompanyId] FOREIGN KEY ([BaseCompanyId]) REFERENCES [dbo].[BaseCompany] ([BaseCompanyId]),
    CONSTRAINT [FK_VendorInvoice_Vendor_VendorId] FOREIGN KEY ([VendorId]) REFERENCES [dbo].[Vendor] ([VendorId])
);